# Generated by radar/scripts/homebrew; review before publishing to ChristianMoesl/homebrew-tap.
class Radar < Formula
  desc "Terminal dashboard for tasks and development workspaces"
  homepage "https://github.com/ChristianMoesl/radar"
  version "1.2.3"
  license "MIT"

  depends_on "fd"
  depends_on "gh"
  depends_on macos: :ventura
  depends_on "tmux"

  on_macos do
    on_arm do
      url "https://github.com/ChristianMoesl/radar/releases/download/v1.2.3/radar_v1.2.3_darwin_arm64.tar.gz"
      sha256 "f69162950f235e3cdbbad33f1f912d1a504be90d8a37d002c735d6f3e3882265"
    end
    on_intel do
      url "https://github.com/ChristianMoesl/radar/releases/download/v1.2.3/radar_v1.2.3_darwin_amd64.tar.gz"
      sha256 "5861314d7fccb39c2192173240eab44fa35ca66426201ca2acd0630a6258dd51"
    end
  end

  def install
    odie "tmux >= 3.2 is required" if Formula["tmux"].version < Version.new("3.2")

    system "/usr/bin/codesign", "--verify", "--strict", "libexec/radar/RadarNotifier.app"
    bin.install "bin/radar"
    man1.install "share/man/man1/radar.1"
    man5.install "share/man/man5/radar-config.5"
    (libexec/"radar").install "libexec/radar/RadarNotifier.app"
    pkgshare.install "share/radar/AGENTS.md", "LICENSE"
  end

  post_install_steps do
    run "/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister",
        args: ["-f", "{{opt_prefix}}/libexec/radar/RadarNotifier.app"]
  end

  def caveats
    <<~EOS
      Git must be available on PATH. Install Pi >= 0.85.1 yourself with
      Node.js >= 24 and npm (https://pi.dev). This formula does not
      install or update Git, Node or Pi.

      Run radar: first launch or missing required tools automatically opens setup.
      Setup checks prerequisites, reviews configuration, creates missing default
      agent instructions, and asks to install the pi-radar extension in your profile.
      Homebrew does not edit user configuration, Pi settings or shell profiles.

      Update with brew upgrade radar, not radar update. Then run radar restart
      if the daemon is running. Update your host pi-radar package separately;
      active Pi sessions need /reload or restart.

      Notifications may need macOS launch approval and notification permission:
        radar setup notifications
      Never disable Gatekeeper or remove quarantine to bypass approval.

      If you previously installed Radar into ~/.local/bin, check `which -a radar`
      and resolve PATH precedence before setup. No existing install is removed.
    EOS
  end

  test do
    assert_match "v#{version}", shell_output("#{bin}/radar version")
    assert_match "radar/config.yaml", shell_output("#{bin}/radar config-path")
    # Deferring only prints guidance; it never opens Settings or requests permission.
    # Launch through a symlink to exercise Homebrew's Cellar-relative asset lookup.
    (testpath/"radar-link").make_symlink bin/"radar"
    output = pipe_output("#{testpath}/radar-link setup notifications", "d\n")
    assert_match "#{libexec}/radar/RadarNotifier.app/Contents/MacOS/radar-notifier", output
    assert_path_exists pkgshare/"AGENTS.md"
    assert_path_exists pkgshare/"LICENSE"
    assert_path_exists man1/"radar.1"
    assert_path_exists man5/"radar-config.5"
    assert_predicate libexec/"radar/RadarNotifier.app/Contents/MacOS/radar-notifier", :executable?
    system "/usr/bin/codesign", "--verify", "--strict", libexec/"radar/RadarNotifier.app"
    refute_path_exists testpath/".config/radar/config.yaml"
  end
end
